apiVersion: v1
kind: Service
metadata:
  name: configsvr
  namespace: mongodb
  labels:
    app: mongodb
    environment: demo
    role: service
spec:
  selector:
    app: mongodb
    environment: demo
    role: configsvr
  clusterIP: None
  ports:
    - name: mongod
      port: 27019
      
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: configsvr-config
  namespace: mongodb
  labels:
    app: mongodb
    environment: demo
    role: configsvr
data:
  configsvr.cnf: |
    sharding:
      clusterRole: configsvr
    replication:
      replSetName: configsvr
    net:
      bindIp: 0.0.0.0
  initiateRS.js: |
    var cfg = {
        "_id":"configsvr"
        ,configsvr:true
        ,"members":[
            {"_id":0,"host":"configsvr-0.configsvr.mongodb.svc.cluster.local:27019"},
            {"_id":1,"host":"configsvr-1.configsvr.mongodb.svc.cluster.local:27019"},
            {"_id":2,"host":"configsvr-2.configsvr.mongodb.svc.cluster.local:27019"}
        ]
    };
    var error = rs.initiate(cfg);
    printjson(error);

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    environment: demo
  name: configsvr-0
spec:
  storageClassName: mongodb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jfenghu/k8s/mnt/mongodb/configsvr-0"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    environment: demo
  name: configsvr-1
spec:
  storageClassName: mongodb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jfenghu/k8s/mnt/mongodb/configsvr-1"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    environment: demo
  name: configsvr-2
spec:
  storageClassName: mongodb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jfenghu/k8s/mnt/mongodb/configsvr-2"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: configsvr
  namespace: mongodb
  labels:
    app: mongodb
    environment: demo
    role: configsvr
spec:
  selector:
    matchLabels:
      app: mongodb
      environment: demo
      role: configsvr
  replicas: 3
  serviceName: configsvr
  template:
    metadata:
      name: configsvr
      labels:
        app: mongodb
        role: configsvr
        environment: demo
    spec:
      volumes:
        - name: config
          configMap:
            name: configsvr-config
      containers:
        - name: mongodb
          image: mongo:3.6
          command:
            - "mongod"
            - "--config=/config/configsvr.cnf"
          ports:
            - name: client
              containerPort: 27019
          livenessProbe:
            exec:
              command: ["mongo", "--port", "27019", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command: ["mongo", "--port", "27019", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: config
              mountPath: /config
            - name: datadir
              mountPath: /data/db
              subPath: configsvr
  volumeClaimTemplates:
    - metadata: 
        name: datadir
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: mongodb
        resources:
          requests:
            storage: 10Gi
    