apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    environment: dev
  name: task-pv-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/home/jfenghu/k8s/mnt/data"
