apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: database
    environment: dev
    release: bana
spec:
  containers:
    - name: redis
      image: redis:3.2-alpine
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}   
