apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: spring
  labels:
    app: support
    environment: demo
    role: trace
spec:
  selector:
    app: support
    environment: demo
    role: trace
  type: NodePort
  ports:
    - name: web
      port: 9411
      nodePort: 31941
