apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
  labels: 
    app: mysql
    tier: backend
    env: demo
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config on the slave.
    [mysqld]
    super-read-only
