apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    tier: namespace
    environment: demo
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
  clusterIP: None
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
    tier: service
    enviroment: demo
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      nodePort: 30306
  type: NodePort
