apiVersion: v1
kind: Service
metadata:
  name: gatewayex
  namespace: pippy
  labels:
    app: gateway
    environment: demo
    role: gateway
spec:
  selector:
    app: gateway
    environment: demo
    role: gateway
  type: NodePort
  ports:
    - name: web
      port: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gateway
  namespace: pippy
  labels:
    app: gateway
    environment: demo
    role: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      environment: demo
      role: gateway
  template:
    metadata:
      name: gateway
      namespace: pippy
      labels:
        app: gateway
        environment: demo
        role: gateway
    spec:
      containers:
        - name: gateway
          image: "ikeeps/pippy-gateway:0.0.1"
          env:
            - name: 'spring.profiles.active'
              value: 'production'
          ports:
            - name: web
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
