apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: spring
  labels:
    app: support
    environment: demo
    role: registry
spec:
  selector:
    app: support
    environment: demo
    role: registry
  clusterIP: None
  ports:
    - name: web
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: registryex
  namespace: spring
  labels:
    app: support
    environment: demo
    role: registryex
spec:
  selector:
    app: support
    environment: demo
    role: registry
  type: NodePort
  ports:
    - name: web
      port: 9000
      nodePort: 30889
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: spring
  labels:
    app: support
    environment: demo
    role: registry
spec:
  selector:
    matchLabels:
      app: support
      environment: demo
      role: registry
  replicas: 2
  serviceName: registry
  template:
    metadata:
      name: registry
      namespace: spring
      labels:
        app: support
        environment: demo
        role: registry
    spec:
      containers:
        - name: registry
          image: "ikeeps/pippy-registry:0.0.1"
          env:
            - name: 'spring.profiles.active'
              value: 'production'
          ports:
            - name: web
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: "/health"
              port: 9000
            initialDelaySeconds: 40
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 9000
            initialDelaySeconds: 40
            timeoutSeconds: 5   
          
          
      